### ISSUE TITLE
Can we define default values for a given key?

### ISSUE THREAD

**Issue by duranmla** [AndreasFaust/gatsby-source-custom-api#13]
Hi! 

In order to avoid more complexity at the development time and maybe crashes at building time due to the possibility of a server not being running can we add default values on a given schema? For instance I have:

```
    {
      resolve: 'gatsby-source-custom-api',
      options: {
        url: `${process.env.GATSBY_COMMUNITY_URL}/about.json`,
        rootKey: 'about',
        schemas: {
          about: `
            user_count: Int
          `
        }
      }
    }
```

Which I would like to say something like:

```
    {
      resolve: 'gatsby-source-custom-api',
      options: {
        url: `${process.env.GATSBY_COMMUNITY_URL}/about.json`,
        rootKey: 'about',
        schemas: {
          about: `
            user_count: Int = 33000 <-- notice the lame attempt here
          `
        }
      }
    }
```

It feels a bit overkill that the entire page crashes cause the server is not available. Any thoughts?
Thanks a lot for this solution btw, really appreciate the work have been done here!

**Comment by baumant** [comment]
This would be done when you actually set up the graphql query on the page, something like:
```
allAbouts( filter:  { user_count: { eq: 33000 } } ) {
  edges {
      node {
        user_count
      }
    }
}
```

**Comment by duranmla** [comment]
But that doesn't quite solve the issue, isn't? So imagine you're starting to build the site and the server is down _(the most easy to describe case will be to do `yarn start` on Gatsby site locally without starting the server)_ This will thrown error like:

![image](https://user-images.githubusercontent.com/1425162/97711399-5c9f0a80-1abd-11eb-95e7-e9badc9f7bee.png)

As the query indeed is not there (notice how I toggle between the GraphiQL when the server with the api is running and when the server with the api is not running in my local) **allAbout** is not created when the server is not available in build time

![http://recordit.co/Pie06Z7D6a](http://recordit.co/Pie06Z7D6a.gif)

And there is a lot going on at https://www.gatsbyjs.com/docs/schema-customization/#creating-type-definitions so I was wondering about a built-in option from `gatsby-source-custom-api` to tackle this scenario

**Comment by baumant** [comment]
Ah I see what you mean, misunderstood your question I thought you were trying to filter your query. This seems to be a common issue with Gatsby.
Read through this issue (https://github.com/gatsbyjs/gatsby/issues/2392), there are a few proposed solutions in there (creating a resolver in gatsby-node)

**Comment by duranmla** [comment]
Got it, I will need to test this out if worth the trouble but in the mean time I would close the issue...Thanks for the replies!!
