### ISSUE TITLE
Does that work with gatsby v4?

### ISSUE THREAD

**Issue by MuhammadHadiofficial** [AndreasFaust/gatsby-source-custom-api#35]
Any reference to migrate this to gatsbyv4?

**Comment by cdennington** [comment]
I just updated a project using this plugin happily to the latest version including GatsbyV4
<img width="227" alt="image" src="https://user-images.githubusercontent.com/1114197/158005624-cfb0d8cf-a7b0-4f6b-aebe-67d1ed0eb6ff.png">

I'm now seeing the following warnings when running gatsby develop:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/1114197/158005673-4e56e155-e2a3-4bb5-afb8-cfa56cd38913.png">
<img width="736" alt="image" src="https://user-images.githubusercontent.com/1114197/158005696-2764867e-e88b-47a5-9967-74b2d6a76cf1.png">

And within my images object local is now null:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/1114197/158005721-409d88e4-5ea8-4ff3-8c8b-e411c6303418.png">

This is how Ive set up the endpoints in Gatsby config:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/1114197/158005769-74a81c07-8046-49cc-90a0-0b109590fa15.png">

This was working as expected in Gatsby 3.7.0

I haven't looked any further into the warning to see if that is the issue stopping the images from working

**Comment by cdennington** [comment]
Further investigation, updating to createSchemaCustomization in gatsby-node fixes the issues, and images are now loading as expected.

Pull request created: https://github.com/AndreasFaust/gatsby-source-custom-api/pull/42/files

**Comment by AndreasFaust** [comment]
Merged and released version `2.3.5`.
