### ISSUE TITLE
"gatsby-source-custom-api" threw an error while running the sourceNodes lifecycle:

### ISSUE THREAD

**Issue by bjatwork** [AndreasFaust/gatsby-source-custom-api#5]
All about this issue  https://github.com/gatsbyjs/gatsby/issues/17628

**Comment by matt-subroot** [comment]
Any solution to this?

**Comment by matt-subroot** [comment]
@bjatwork Open up the node-module, go to the utils folder, open up buildNode.js and delete line 14, 
      url: data && data.url,

I'll submit a PR at some point, but this will get it running at least

**Comment by bjatwork** [comment]
@matt-subroot  thanks

**Comment by shallow-alchemy** [comment]
@AndreasFaust Can you please merge or handle the url key your own way so we can use this. Thanks

**Comment by AndreasFaust** [comment]
Thank you, @matt-subroot !
I have just merged the PR.
